-- Raptor factories for the player factions, offered to constructors by unitbasedefs/modded_arsenal.lua when the
-- raptorscavarsenal modoption is on. Their raptor build options only exist once the raptor unit files are loaded.

local factories = {
	brood_nest = {
		tier = 1,
		metalcost = 650,
		energycost = 1600,
		buildtime = 9000,
		health = 3600,
		workertime = 150,
		collision = "70 50 70",
		buildoptions = {
			"raptor_land_swarmer_basic_t1_v1",
			"raptor_land_swarmer_heal_t1_v1",
			"raptor_land_swarmer_basic_t2_v1",
			"raptor_land_swarmer_basic_t2_v2",
			"raptor_land_swarmer_basic_t2_v3",
			"raptor_land_swarmer_basic_t2_v4",
			"raptor_land_swarmer_heal_t2_v1",
			"raptor_land_swarmer_acids_t2_v1",
			"raptor_land_swarmer_emp_t2_v1",
			"raptor_land_swarmer_fire_t2_v1",
			"raptor_land_swarmer_brood_t2_v1",
			"raptor_land_kamikaze_basic_t2_v1",
			"raptor_land_kamikaze_emp_t2_v1",
			"raptor_land_spiker_basic_t2_v1",
			"raptor_allterrain_swarmer_basic_t2_v1",
			"raptor_allterrain_swarmer_acid_t2_v1",
			"raptor_allterrain_swarmer_emp_t2_v1",
			"raptor_allterrain_swarmer_fire_t2_v1",
			"raptorh1b",
		},
	},
	brood_roost = {
		tier = 1,
		metalcost = 750,
		energycost = 2400,
		buildtime = 10000,
		health = 3000,
		workertime = 150,
		collision = "70 50 70",
		buildoptions = {
			"raptor_air_fighter_basic_t1_v1",
			"raptor_air_bomber_basic_t1_v1",
			"raptor_air_scout_basic_t2_v1",
			"raptor_air_fighter_basic_t2_v1",
			"raptor_air_fighter_basic_t2_v2",
			"raptor_air_fighter_basic_t2_v3",
			"raptor_air_fighter_basic_t2_v4",
			"raptor_air_bomber_basic_t2_v1",
			"raptor_air_bomber_basic_t2_v2",
			"raptor_air_bomber_acid_t2_v1",
			"raptor_air_bomber_emp_t2_v1",
			"raptor_air_gunship_basic_t2_v1",
			"raptor_air_gunship_acid_t2_v1",
			"raptor_air_gunship_antiair_t2_v1",
			"raptor_air_gunship_emp_t2_v1",
			"raptor_air_gunship_fire_t2_v1",
			"raptor_air_kamikaze_basic_t2_v1",
		},
	},
	brood_lair = {
		tier = 2,
		metalcost = 2600,
		energycost = 14000,
		buildtime = 26000,
		health = 9000,
		workertime = 400,
		collision = "90 64 90",
		buildoptions = {
			"raptor_land_swarmer_basic_t3_v1",
			"raptor_land_swarmer_basic_t3_v2",
			"raptor_land_swarmer_basic_t3_v3",
			"raptor_land_swarmer_spectre_t3_v1",
			"raptor_land_swarmer_brood_t3_v1",
			"raptor_land_swarmer_heal_t3_v1",
			"raptor_allterrain_swarmer_basic_t3_v1",
			"raptor_land_assault_basic_t2_v1",
			"raptor_land_assault_basic_t2_v2",
			"raptor_land_assault_basic_t2_v3",
			"raptor_land_assault_acid_t2_v1",
			"raptor_land_assault_emp_t2_v1",
			"raptor_land_assault_spectre_t2_v1",
			"raptor_allterrain_assault_basic_t2_v1",
			"raptor_allterrain_assault_basic_t2_v2",
			"raptor_allterrain_assault_basic_t2_v3",
			"raptor_allterrain_assault_acid_t2_v1",
			"raptor_allterrain_assault_emp_t2_v1",
			"raptor_allterrain_arty_basic_t2_v1",
			"raptor_allterrain_arty_acid_t2_v1",
			"raptor_allterrain_arty_emp_t2_v1",
			"raptor_allterrain_arty_brood_t2_v1",
			"raptorartillery",
			"raptor_6legged_l",
			"raptorh5",
			"raptor_air_scout_basic_t3_v1",
		},
	},
	brood_throne = {
		tier = 3,
		metalcost = 9000,
		energycost = 90000,
		buildtime = 90000,
		health = 30000,
		workertime = 2000,
		collision = "110 80 110",
		buildoptions = {
			"raptor_land_swarmer_basic_t4_v1",
			"raptor_land_swarmer_basic_t4_v2",
			"raptor_land_swarmer_spectre_t4_v1",
			"raptor_land_swarmer_brood_t4_v1",
			"raptor_land_swarmer_fire_t4_v1",
			"raptor_land_swarmer_heal_t4_v1",
			"raptor_allterrain_swarmer_basic_t4_v1",
			"raptor_land_spiker_basic_t4_v1",
			"raptor_land_spiker_spectre_t4_v1",
			"raptor_land_kamikaze_basic_t4_v1",
			"raptor_land_kamikaze_emp_t4_v1",
			"raptor_land_assault_basic_t4_v1",
			"raptor_land_assault_basic_t4_v2",
			"raptor_land_assault_spectre_t4_v1",
			"raptor_allterrain_assault_basic_t4_v1",
			"raptor_allterrain_assault_basic_t4_v2",
			"raptor_allterrain_arty_basic_t4_v1",
			"raptor_allterrain_arty_acid_t4_v1",
			"raptor_allterrain_arty_emp_t4_v1",
			"raptor_allterrain_arty_brood_t4_v1",
			"raptor_air_fighter_basic_t4_v1",
			"raptor_air_bomber_basic_t4_v1",
			"raptor_air_bomber_basic_t4_v2",
			"raptor_air_bomber_brood_t4_v2",
			"raptor_air_bomber_brood_t4_v3",
			"raptor_air_bomber_brood_t4_v4",
			"raptor_air_scout_basic_t4_v1",
			"raptor_matriarch_basic",
			"raptor_matriarch_acid",
			"raptor_matriarch_electric",
			"raptor_matriarch_fire",
			"raptor_matriarch_healer",
			"raptor_matriarch_spectre",
			"raptor_queen_veryeasy",
		},
	},
}

local unitDefs = {}
for name, f in pairs(factories) do
	unitDefs[name] = {
		buildangle = 1024,
		builder = true,
		buildpic = "modded/" .. name .. ".dds",
		buildtime = f.buildtime,
		canmove = true,
		canreclaim = false,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = f.collision,
		collisionvolumetype = "CylY",
		energycost = f.energycost,
		explodeas = "largeBuildingExplosionGeneric",
		footprintx = 6,
		footprintz = 6,
		health = f.health,
		icontype = "raptor_hive",
		maxacc = 0,
		maxdec = 0,
		maxslope = 15,
		maxwaterdepth = 0,
		metalcost = f.metalcost,
		objectname = "Modded/" .. name .. ".s3o",
		script = "Units/modded/brood_factory_lus.lua",
		seismicsignature = 0,
		selfdestructas = "largeBuildingExplosionGenericSelfd",
		sightdistance = 300,
		workertime = f.workertime,
		yardmap = "oeeeeooeeeeooeeeeooeeeeooeeeeooeeeeo",
		buildoptions = f.buildoptions,
		customparams = {
			model_author = "FireStorm, Beherith",
			normaltex = "unittextures/chicken_l_normals.png",
			subfolder = "Modded",
			techlevel = f.tier,
			unitgroup = f.tier == 1 and "builder" or ("buildert" .. f.tier),
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:blood_spray",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			unitcomplete = "unitready",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			select = {
				[1] = "bigraptorroar",
			},
		},
	}
end

return unitDefs
