-- Structures placed by Steve (units/Modded/steve.lua). Nether portal teleporting lives in
-- luarules/gadgets/unit_minecraft_nether_portal.lua, the TNT fuse in luarules/gadgets/unit_minecraft_tnt.lua.

local function blockSounds()
	return {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "servtny1",
		},
	}
end

local function block(name, health, metalcost, buildtime)
	return {
		blocking = true,
		buildpic = "modded/" .. name .. ".dds",
		buildtime = buildtime,
		canattack = false,
		canrepeat = false,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "16 16 16",
		collisionvolumetype = "Box",
		crushresistance = 250,
		energycost = 0,
		explodeas = "mc_block_break",
		footprintx = 2,
		footprintz = 2,
		health = health,
		hidedamage = true,
		icontype = "armdrag",
		levelground = false,
		maxacc = 0,
		maxdec = 0,
		maxslope = 64,
		maxwaterdepth = 0,
		metalcost = metalcost,
		objectname = "Modded/" .. name .. ".s3o",
		script = "Units/modded/mc_block_lus.lua",
		seismicsignature = 0,
		selfdestructas = "mc_block_break",
		selfdestructcountdown = 1,
		sightdistance = 1,
		yardmap = "ffff",
		customparams = {
			model_author = "Beyond All Reason Modded",
			normaltex = "unittextures/blank_normal.dds",
			objectify = true,
			paralyzemultiplier = 0,
			removestop = true,
			removewait = true,
			subfolder = "Modded",
			unitgroup = "util",
		},
		sounds = blockSounds(),
	}
end

return {
	mc_dirt = block("mc_dirt", 900, 3, 70),
	mc_cobble = block("mc_cobble", 3000, 10, 220),

	mc_tnt = {
		blocking = true,
		buildpic = "modded/mc_tnt.dds",
		buildtime = 900,
		canattack = false,
		canrepeat = false,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "16 16 16",
		collisionvolumetype = "Box",
		energycost = 1800,
		explodeas = "mc_tnt_blast",
		footprintx = 2,
		footprintz = 2,
		health = 260,
		icontype = "armmine1",
		levelground = false,
		maxacc = 0,
		maxdec = 0,
		maxslope = 64,
		maxwaterdepth = 0,
		metalcost = 70,
		objectname = "Modded/mc_tnt.s3o",
		script = "Units/modded/mc_tnt_lus.lua",
		seismicsignature = 0,
		selfdestructas = "mc_tnt_blast",
		selfdestructcountdown = 2,
		sightdistance = 200,
		yardmap = "oooo",
		customparams = {
			model_author = "Beyond All Reason Modded",
			normaltex = "unittextures/blank_normal.dds",
			removestop = true,
			removewait = true,
			subfolder = "Modded",
			tnt_fuse = 2.5,
			tnt_trigger_radius = 150,
			unitgroup = "explo",
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:tnt-fuse",
			},
		},
		sounds = blockSounds(),
	},

	mc_nether_portal = {
		blocking = false,
		buildpic = "modded/mc_nether_portal.dds",
		buildtime = 5000,
		canattack = false,
		canrepeat = false,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "32 40 8",
		collisionvolumetype = "Box",
		energycost = 4000,
		explodeas = "mediumBuildingExplosionGeneric",
		footprintx = 4,
		footprintz = 2,
		health = 3200,
		icontype = "armjuno",
		levelground = false,
		maxacc = 0,
		maxdec = 0,
		maxslope = 20,
		maxwaterdepth = 0,
		metalcost = 320,
		objectname = "Modded/mc_nether_portal.s3o",
		script = "Units/modded/mc_portal_lus.lua",
		seismicsignature = 0,
		selfdestructas = "mediumBuildingExplosionGenericSelfd",
		sightdistance = 300,
		customparams = {
			model_author = "Beyond All Reason Modded",
			nether_portal = true,
			normaltex = "unittextures/blank_normal.dds",
			portal_radius = 30,
			removestop = true,
			removewait = true,
			subfolder = "Modded",
			unitgroup = "util",
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:nether-portal-ambient",
				[2] = "custom:nether-teleport",
			},
		},
		sounds = blockSounds(),
	},
}
