-- Effects for the modded units: Sukuna's slashes and Domain Expansion, and Steve's nether portals and TNT.

local function slash(size, count)
	return {
		streaks = {
			air = true,
			class = [[CSimpleParticleSystem]],
			count = 1,
			ground = true,
			water = true,
			underwater = true,
			unit = true,
			nounit = true,
			properties = {
				airdrag = 0.55,
				colormap = [[1 1 1 0.05   1 0.3 0.25 0.04   0.6 0 0 0.02   0 0 0 0]],
				directional = true,
				emitrot = 30,
				emitrotspread = 120,
				emitvector = [[0, 1, 0]],
				gravity = [[0, 0, 0]],
				numparticles = count,
				particlelife = 7,
				particlelifespread = 3,
				particlesize = size,
				particlesizespread = size * 0.6,
				particlespeed = size * 0.4,
				particlespeedspread = size * 0.3,
				pos = [[0, 4, 0]],
				sizegrowth = 1.2,
				sizemod = 1,
				texture = [[laserend]],
				useairlos = false,
			},
		},
		sparks = {
			air = true,
			class = [[CSimpleParticleSystem]],
			count = 1,
			ground = true,
			unit = true,
			nounit = true,
			properties = {
				airdrag = 0.85,
				colormap = [[1 0.4 0.3 0.02   0.7 0.05 0.05 0.01   0 0 0 0]],
				directional = true,
				emitrot = 10,
				emitrotspread = 70,
				emitvector = [[0, 1, 0]],
				gravity = [[0, -0.2, 0]],
				numparticles = count + 2,
				particlelife = 9,
				particlelifespread = 5,
				particlesize = size * 0.15,
				particlesizespread = size * 0.1,
				particlespeed = 2,
				particlespeedspread = 2,
				pos = [[0, 4, 0]],
				sizegrowth = 0,
				sizemod = 1,
				texture = [[gunshotglow]],
				useairlos = false,
			},
		},
		flash = {
			class = [[CSimpleGroundFlash]],
			count = 1,
			air = false,
			ground = true,
			water = true,
			properties = {
				colormap = [[0.8 0.05 0.05 0.5   0 0 0 0.01]],
				size = size * 1.2,
				sizegrowth = 0,
				ttl = 10,
				texture = [[groundflash]],
			},
		},
	}
end

local function shrineOpen(radius)
	return {
		darkness = {
			class = [[CSimpleGroundFlash]],
			count = 1,
			air = false,
			ground = true,
			water = true,
			underwater = true,
			properties = {
				colormap = [[0.6 0.02 0.02 0.9   0.25 0 0 0.6   0 0 0 0.01]],
				size = radius,
				sizegrowth = 0,
				ttl = 40,
				texture = [[groundflash]],
			},
		},
		ring = {
			class = [[CSimpleGroundFlash]],
			count = 1,
			air = false,
			ground = true,
			water = true,
			underwater = true,
			properties = {
				colormap = [[1 0.15 0.1 1   0.6 0 0 0.6   0 0 0 0.01]],
				size = 40,
				sizegrowth = (radius - 40) / 18,
				ttl = 18,
				texture = [[groundring]],
			},
		},
		shrine = {
			air = true,
			class = [[CSimpleParticleSystem]],
			count = 1,
			ground = true,
			water = true,
			properties = {
				airdrag = 0.92,
				colormap = [[0.5 0.02 0.02 0.6   0.2 0 0 0.5   0.05 0 0 0.3   0 0 0 0]],
				directional = false,
				emitrot = 0,
				emitrotspread = 25,
				emitvector = [[0, 1, 0]],
				gravity = [[0, 0.05, 0]],
				numparticles = 18,
				particlelife = 60,
				particlelifespread = 30,
				particlesize = radius * 0.08,
				particlesizespread = radius * 0.06,
				particlespeed = 2,
				particlespeedspread = 3,
				pos = [[0, 10, 0]],
				sizegrowth = 0.6,
				sizemod = 1,
				texture = [[smoke_puff_red]],
				useairlos = false,
			},
		},
	}
end

local function shrineFloor(radius)
	return {
		darkness = {
			class = [[CSimpleGroundFlash]],
			count = 1,
			air = false,
			ground = true,
			water = true,
			underwater = true,
			properties = {
				colormap = [[0.35 0 0 0.55   0.35 0 0 0.55   0 0 0 0.01]],
				size = radius,
				sizegrowth = 0,
				ttl = 20,
				texture = [[groundflash]],
			},
		},
	}
end

local definitions = {
	["sukuna-slash"] = slash(10, 2),
	["sukuna-slash-large"] = slash(18, 3),

	["malevolent-shrine-open"] = shrineOpen(380),
	["malevolent-shrine-open-xl"] = shrineOpen(520),
	["malevolent-shrine-floor"] = shrineFloor(380),
	["malevolent-shrine-floor-xl"] = shrineFloor(520),

	["domain-boundary"] = {
		pillar = {
			air = true,
			class = [[CSimpleParticleSystem]],
			count = 1,
			ground = true,
			water = true,
			properties = {
				airdrag = 0.9,
				colormap = [[0.9 0.1 0.05 0.4   0.4 0.02 0.02 0.3   0.05 0 0 0.1   0 0 0 0]],
				directional = false,
				emitrot = 0,
				emitrotspread = 10,
				emitvector = [[0, 1, 0]],
				gravity = [[0, 0.25, 0]],
				numparticles = 2,
				particlelife = 18,
				particlelifespread = 8,
				particlesize = 7,
				particlesizespread = 4,
				particlespeed = 1.5,
				particlespeedspread = 1,
				pos = [[0, 2, 0]],
				sizegrowth = 0.4,
				sizemod = 1,
				texture = [[flame]],
				useairlos = false,
			},
		},
	},

	["nether-teleport"] = {
		swirl = {
			air = true,
			class = [[CSimpleParticleSystem]],
			count = 1,
			ground = true,
			water = true,
			unit = true,
			nounit = true,
			properties = {
				airdrag = 0.9,
				colormap = [[0.8 0.3 1 0.6   0.5 0.1 0.9 0.4   0.2 0 0.4 0.2   0 0 0 0]],
				directional = false,
				emitrot = 0,
				emitrotspread = 180,
				emitvector = [[0, 1, 0]],
				gravity = [[0, 0.15, 0]],
				numparticles = 24,
				particlelife = 25,
				particlelifespread = 15,
				particlesize = 3,
				particlesizespread = 3,
				particlespeed = 1.5,
				particlespeedspread = 2,
				pos = [[0, 12, 0]],
				sizegrowth = -0.05,
				sizemod = 1,
				texture = [[randdots]],
				useairlos = false,
			},
		},
		flash = {
			class = [[CSimpleGroundFlash]],
			count = 1,
			air = false,
			ground = true,
			water = true,
			properties = {
				colormap = [[0.6 0.2 1 0.8   0.3 0 0.6 0.4   0 0 0 0.01]],
				size = 40,
				sizegrowth = 0,
				ttl = 20,
				texture = [[groundflash]],
			},
		},
	},

	["nether-portal-ambient"] = {
		motes = {
			air = true,
			class = [[CSimpleParticleSystem]],
			count = 1,
			ground = true,
			water = true,
			properties = {
				airdrag = 0.95,
				colormap = [[0.7 0.3 1 0.5   0.4 0.1 0.8 0.3   0 0 0 0]],
				directional = false,
				emitrot = 70,
				emitrotspread = 40,
				emitvector = [[0, 1, 0]],
				gravity = [[0, 0.04, 0]],
				numparticles = 2,
				particlelife = 30,
				particlelifespread = 20,
				particlesize = 1.5,
				particlesizespread = 1.5,
				particlespeed = 0.4,
				particlespeedspread = 0.6,
				pos = [[-8 r16, -10 r20, -2 r4]],
				sizegrowth = 0,
				sizemod = 1,
				texture = [[randdots]],
				useairlos = false,
			},
		},
	},

	["tnt-fuse"] = {
		sparks = {
			air = true,
			class = [[CSimpleParticleSystem]],
			count = 1,
			ground = true,
			properties = {
				airdrag = 0.9,
				colormap = [[1 0.9 0.5 0.03   1 0.5 0.1 0.02   0 0 0 0]],
				directional = true,
				emitrot = 0,
				emitrotspread = 50,
				emitvector = [[0, 1, 0]],
				gravity = [[0, -0.15, 0]],
				numparticles = 3,
				particlelife = 8,
				particlelifespread = 6,
				particlesize = 1.5,
				particlesizespread = 1,
				particlespeed = 1.5,
				particlespeedspread = 1.5,
				pos = [[0, 17, 0]],
				sizegrowth = 0,
				sizemod = 1,
				texture = [[gunshotglow]],
				useairlos = false,
			},
		},
		smoke = {
			air = true,
			class = [[CSimpleParticleSystem]],
			count = 1,
			ground = true,
			properties = {
				airdrag = 0.95,
				colormap = [[0.3 0.3 0.3 0.4   0.15 0.15 0.15 0.2   0 0 0 0]],
				directional = false,
				emitrot = 0,
				emitrotspread = 15,
				emitvector = [[0, 1, 0]],
				gravity = [[0, 0.1, 0]],
				numparticles = 1,
				particlelife = 20,
				particlelifespread = 10,
				particlesize = 3,
				particlesizespread = 2,
				particlespeed = 0.5,
				particlespeedspread = 0.5,
				pos = [[0, 17, 0]],
				sizegrowth = 0.15,
				sizemod = 1,
				texture = [[smoke_puff]],
				useairlos = false,
			},
		},
	},
}

return definitions
